/*
 * The options parseArgs accepts, for every command. Kept apart from cli.ts (which runs on
 * import) so the tests can check that help.ts names exactly these.
 */
export const CLI_OPTIONS = {
  out: { type: 'string' },
  'no-write': { type: 'boolean' },
  routes: { type: 'string' },
  config: { type: 'string' },
  format: { type: 'string' },
  json: { type: 'boolean' },
  'fail-on': { type: 'string' },
  header: { type: 'string', multiple: true },
  env: { type: 'string', multiple: true },
  timeout: { type: 'string' },
  'no-auth': { type: 'boolean' },
  port: { type: 'string' },
  scope: { type: 'string' },
  'client-id': { type: 'string' },
  'client-secret': { type: 'string' },
  processes: { type: 'string' },
  versions: { type: 'string' },
  release: { type: 'string' },
  'server-version-is-release': { type: 'boolean' },
  'include-prereleases': { type: 'boolean' },
  arg: { type: 'string', multiple: true },
  bin: { type: 'string' },
  cmd: { type: 'string' },
  'allow-scripts': { type: 'boolean' },
  'install-timeout': { type: 'string' },
  csv: { type: 'string' },
  'keep-installs': { type: 'boolean' },
  scenario: { type: 'string' },
  plan: { type: 'boolean' },
  init: { type: 'boolean' },
  'union-out': { type: 'string' },
  auto: { type: 'boolean' },
  'with-session': { type: 'boolean' },
  catalog: { type: 'boolean' },
  'open-world': { type: 'boolean' },
  'max-calls': { type: 'string' },
  'max-calls-per-unlock': { type: 'string' },
  'save-scenario': { type: 'string' },
  value: { type: 'string', multiple: true },
  'values-file': { type: 'string' },
  'assume-read-only': { type: 'string', multiple: true },
  help: { type: 'boolean', short: 'h' },
  version: { type: 'boolean', short: 'v' },
} as const;
